### ISSUE TITLE
brnn wrong

### ISSUE THREAD

**Issue by meanmee** [EderSantana/seya#10]
/usr/bin/python2.7 /home/eelab/wxm/my_ex/brnn-speech/models/brnn.py
Using gpu device 0: GeForce GTX 970
Loading data...
/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_perform_ext.py:133: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  from scan_perform.scan_perform import *
20000 train sequences
5000 test sequences
Pad sequences (samples x time)
X_train shape: (20000, 100)
X_test shape: (5000, 100)
Build model...
Train...
Train on 20000 samples, validate on 5000 samples
Epoch 1/4
Traceback (most recent call last):
  File "/home/eelab/wxm/my_ex/brnn-speech/models/brnn.py", line 66, in <module>
    model.fit(X_train, y_train, batch_size=batch_size, nb_epoch=4, validation_data=(X_test, y_test), show_accuracy=True)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 489, in fit
    shuffle=shuffle, metrics=metrics)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 210, in _fit
    outs = f(*ins_batch)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()
ValueError: dimension mismatch in args to gemm (32,64)x(128,1)->(32,1)
Apply node that caused the error: GpuDot22(GpuElemwise{mul,no_inplace}.0, <CudaNdarrayType(float32, matrix)>)
Inputs types: [CudaNdarrayType(float32, matrix), CudaNdarrayType(float32, matrix)]
Inputs shapes: [(32, 64), (128, 1)]
Inputs strides: [(64, 1), (1, 0)]
Inputs values: ['not shown', 'not shown']

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

Process finished with exit code 1

**Comment by EderSantana** [comment]
![screen shot 2015-11-04 at 8 35 11 pm](https://cloud.githubusercontent.com/assets/3902480/10958890/c77912b6-8340-11e5-80da-a8f16c2e35c0.png)

**Comment by EderSantana** [comment]
see details here #5
