### ISSUE TITLE
Question about new Recurrent Layers in recurrent.py

### ISSUE THREAD

**Issue by rahulmohan** [EderSantana/seya#3]
Hi,

I was going through the new recurrent layers you have implemented (GRUM, GRUM2, ExoGRUM, SingleCell). Do you have any references which were the inspiration for these layers? I am very interested in learning more about them, and am intrigued by the additional "memory" component that seems to be added on to the traditional GRU.

Thanks!

**Comment by EderSantana** [comment]
They are my own inventions, but still in experimental phase. I think I should mention that in the code, right? Sorry for not having documentation enough.

Basically, I was trying some sort global stateful memory mechanism. Their usage involves updating states with callbacks. My first experiments were not really good, though (they were not better than regular GRUs). I should post more details in a near future. I'm just organizing more results now. But let me know if you find anything.

**Comment by hugman** [comment]
Dear @EderSantana  

Is your recurrent layer  is compatible with new shape inference Keras Api?

Could you show some examples for implementing complex RNN with your recurrent api only?

**Comment by EderSantana** [comment]
I don't think so. I was still using the previous API.
Right now I'm developing other stuff for my thesis proposal. But I should be back by the end of this month.
I'll update the API and add some new stuff later. I hope you don't mind waiting a little bit.
For know, you check the examples and this code: 
https://github.com/EderSantana/seya/blob/master/tests/test_containers.py#L69-L83

That is all I have for now. Thanks for the attention to this work!!!

**Comment by hugman** [comment]
Ok. thank you for answer.  I'll figure out how to use and extend it.  Good luck to your thesis.
