### ISSUE TITLE
Output shape caclulation in spatial transformer

### ISSUE THREAD

**Issue by SulemanKazi** [EderSantana/seya#33]
In [attention.py](https://github.com/EderSantana/seya/blob/master/seya/layers/attention.py#L53)  where we're getting output shape for spatial transformer:
    
        return (None, int(input_shape[1]),
                int(input_shape[2] / self.downsample_factor),
                int(input_shape[2] / self.downsample_factor))`

Shouldnt this be:

     return (None, int(input_shape[1]),
                int(input_shape[2] / self.downsample_factor),
                int(input_shape[3] / self.downsample_factor))`

This is in the method  `get_output_shape_for` in the keras1 branch and property `output_shape` in the master branch. As it is currently, the output of spatial transformer layer is always a square.

**Comment by EderSantana** [comment]
yeah, I noticed that... I think I did the change in a personal project and it worked.
do you wanna submit a pull request?

**Comment by SulemanKazi** [comment]
Done! (for both master and keras1 branches)

**Comment by EderSantana** [comment]
Thank you! twice!!! :D
