### ISSUE TITLE
Questions about stateful GRU

### ISSUE THREAD

**Issue by hugman** [EderSantana/seya#4]
First, thank you for sharing stateful RNN(GRU) code. 

I checked SGRU and the imdb examples for text generation. 
It looks like
* state reset or modifying is triggered when special callback conditions is met
* in example code, the trigger is 'every N batch'

Probably, we can extend your code to any state change with any callback condition. correct?

One more simple question. 
What's the main advantages of stateful RNN over normal RNN?
Is it just for controlling state?

**Comment by EderSantana** [comment]
There will be advantage when you have long sequences that you have to break into several batches. You know that we usually max the input sequence to 100 elements, right? But some phrases, in nlp for instance, are larger than that. Than we put part of the phrase in one batch and the rest in others. But if you clean up the hidden state after every batch your network won't actually have the right context.

I believe the imdb dataset does not have that problem. In that case, I think you will prefer the feature I'll introduce next "adaptive initial states". ;) stay tuned and thanks for you interest and kind words!!!

**Comment by hugman** [comment]
Thank you. Now I understood usage of stateful rnn. I am looking forward to adaptive initial state thing. :) 

I will close this issue.

**Comment by LeavesBreathe** [comment]
I wanted to ask more about the advantages of stateful rnn's. @EderSantana you mentioned that if you go longer than 100 input sequences, you should use a stateful rnn. Why is this the case?

Are you saying that a single LSTM/GRU 'memory' starts to diminish after 100 timesteps? Does it do a much better job on 10 timesteps than 100 timesteps?

If this is the case, wouldn't it be more advantageous to do 10 timesteps then perform the next batch? I'm sorry if some of these questions don't make sense. I'm just really confused as to what is being done, but it looks really cool.

**Comment by EderSantana** [comment]
we used to fix it up to 100 to avoid Theano exploding gpu memory or gradients from growing to large. Now we know better and it is easier to vanish a gradient than to explode it.

stateful is similar to using `truncate_gradiente` that also avoids iterations that are too deep in time, but is still better than restart the hidden state to zero. Use stateful when your sentence is longer than you can fit in a sample. Also, make sure the next batch continues the sequences.

**Comment by LeavesBreathe** [comment]
> Also, make sure the next batch continues the sequences.

Okay let me ask you this then: Is there an advantage to *not* randomizing your sequences, and always using a stateful GRU?

Right now, I'm feeding two sentences, and asking it to predict the next sentence. These sentences are from articles/textbooks on astronomy. 

I can easily fit two sentences (about 50 words) with no gpu memory problems. Additionally, I know that when you use ```model.fit```, Keras will randomize your sequences. But if I did *not* randomize them, would a stateful GRU be helpful here? 

I guess what I'm asking is: Would it learn that the previous sequence is related to the next sequence? That way, when its predicting, it predicts a sentence. Then, you feed it the predicted sentence it just produced. Afterwards, without resetting its states, it goes ahead and predicts the next sentence. 

I hate asking you so many questions, so if there is a paper or guide you would rather me read, I'm totally for it. Don't want carpal tunnel exacerbated!

**Comment by LeavesBreathe** [comment]
This makes much more sense. Its good to know that this is available!
