### ISSUE TITLE
BatchNormalization build() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by AkashDevgun** [EderSantana/seya#49]
Hi guys, 

Please help me out for this error. I am running keras and when following line executes it gives the error. 

model.add(BatchNormalization(mode = 1))

raceback (most recent call last):
  File "training.py", line 134, in <module>
    model.add(BatchNormalization(mode = 1))
  File "/home/akash/anaconda2/envs/vision/lib/python2.7/site-packages/keras/models.py", line 324, in add
    output_tensor = layer(self.outputs[0])
  File "/home/akash/anaconda2/envs/vision/lib/python2.7/site-packages/keras/engine/topology.py", line 491, in __call__
    self.build(input_shapes[0])
TypeError: build() takes exactly 1 argument (2 given)
TypeError: build() takes exactly 1 argument (2 given)

**Comment by EderSantana** [comment]
this is a keras issue. also please note that seya does not officially support keras 1.
I'd recommend checking the API of the BatchNormalization in your version of keras to make sure you're using it right
